version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.1
    - 7.0.3
    - 7.0.4
  - dependency-name: chrome-aws-lambda
    versions:
    - 7.0.0
    - 7.0.0
  - dependency-name: puppeteer-core
    versions:
    - 7.0.1
    - 7.0.3
  - dependency-name: markdown-it-anchor
    versions:
    - 7.0.1
